CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER PRIMARY KEY,
    genre_name varchar
);

CREATE TABLE IF NOT EXISTS mpa_rating (
    rating_id INTEGER PRIMARY KEY,
    rating_name varchar
);

CREATE TABLE IF NOT EXISTS users(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar NOT NULL,
    nickname varchar NOT NULL,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS film(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name varchar(50) NOT NULL,
    description varchar(300) NOT NULL,
    release_date DATE,
    duration int NOT NULL,
    rating_id int REFERENCES mpa_rating(rating_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES film(film_id),
    genre_id integer REFERENCES genre(genre_id)
);

CREATE TABLE IF NOT EXISTS status(
	status_id INTEGER PRIMARY KEY,
	name boolean
);

CREATE TABLE IF NOT EXISTS friends_list (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(user_id),
    friend_id integer REFERENCES users(user_id),
    status_id integer REFERENCES status(status_id)
);

CREATE TABLE IF NOT EXISTS like_list  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES film(film_id),
    user_id integer REFERENCES users(user_id)
);



